// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AddressesDbContext))]
    partial class AddressesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Address.AddressElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("IsActive")
                        .HasColumnType("integer")
                        .HasColumnName("isactive");

                    b.Property<int>("IsActual")
                        .HasColumnType("integer")
                        .HasColumnName("isactual");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("objectguid");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("objectid");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("typename");

                    b.HasKey("Id");

                    b.ToTable("as_addr_obj", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Address.AddressHierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("objectid");

                    b.Property<int>("ParentObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("parentobjid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.ToTable("as_adm_hierarchy", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Address.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstAdditionalNumber")
                        .HasColumnType("text")
                        .HasColumnName("addnum1");

                    b.Property<int?>("FirstAdditionalType")
                        .HasColumnType("integer")
                        .HasColumnName("addtype1");

                    b.Property<int>("IsActive")
                        .HasColumnType("integer")
                        .HasColumnName("isactive");

                    b.Property<int>("IsActual")
                        .HasColumnType("integer")
                        .HasColumnName("isactual");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("housenum");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("objectguid");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("objectid");

                    b.Property<string>("SecondAdditionalNumber")
                        .HasColumnType("text")
                        .HasColumnName("addnum2");

                    b.Property<int?>("SecondAdditionalType")
                        .HasColumnType("integer")
                        .HasColumnName("addtype2");

                    b.Property<int?>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("housetype");

                    b.HasKey("Id");

                    b.ToTable("as_houses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
